# Generated by Django 2.1 on 2018-09-17 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='model_cars',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=128)),
                ('make', models.CharField(max_length=128)),
                ('mileage', models.CharField(max_length=128)),
                ('color', models.CharField(max_length=128)),
                ('engine', models.CharField(max_length=128)),
                ('moreinfo', models.CharField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='model_carspic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic', models.ImageField(upload_to='')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carpic', to='info_app.model_cars')),
            ],
        ),
    ]
