# Generated by Django 2.1 on 2018-09-17 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info_app', '0002_model_cars_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='model_cars',
            name='price',
            field=models.CharField(default=5000, max_length=128),
            preserve_default=False,
        ),
    ]
