# Generated by Django 2.1 on 2018-09-18 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info_app', '0003_model_cars_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model_carspic',
            name='pic',
            field=models.ImageField(upload_to='static/images/cars/'),
        ),
    ]
