# Generated by Django 2.1 on 2018-09-18 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info_app', '0011_model_carspic_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='model_carspic',
            name='test',
        ),
    ]
