# Generated by Django 2.1 on 2018-09-18 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info_app', '0012_remove_model_carspic_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='model_cars',
            name='headpic',
            field=models.ImageField(default=12, upload_to=''),
            preserve_default=False,
        ),
    ]
