# Generated by Django 2.1.1 on 2018-12-27 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info_app', '0016_auto_20181227_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model_cars',
            name='moreinfo',
            field=models.TextField(max_length=1024),
        ),
    ]
